// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHACkv7l2Wzj1dkRcAeBCdmjkj4ufqoFQ',
    appId: '1:914960134900:web:becacc5cb260b57e2864a1',
    messagingSenderId: '914960134900',
    projectId: 'cinemon-5e0e1',
    authDomain: 'cinemon-5e0e1.firebaseapp.com',
    storageBucket: 'cinemon-5e0e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-PeJ99xtuZeiuDvpkRWTnQcL-2yaKx0E',
    appId: '1:914960134900:android:7f92c410f6c3aac62864a1',
    messagingSenderId: '914960134900',
    projectId: 'cinemon-5e0e1',
    authDomain: 'cinemon-5e0e1.firebaseapp.com',
    storageBucket: 'cinemon-5e0e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3CgM2GorNdZ7yIFLzd6VbjlzYOtQdnKM',
    appId: '1:914960134900:ios:d62720c76c5db6322864a1',
    messagingSenderId: '914960134900',
    projectId: 'cinemon-5e0e1',
    authDomain: 'cinemon-5e0e1.firebaseapp.com',
    storageBucket: 'cinemon-5e0e1.firebasestorage.app',
    iosBundleId: 'com.cinemon.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3CgM2GorNdZ7yIFLzd6VbjlzYOtQdnKM',
    appId: '1:914960134900:ios:d62720c76c5db6322864a1',
    messagingSenderId: '914960134900',
    projectId: 'cinemon-5e0e1',
    authDomain: 'cinemon-5e0e1.firebaseapp.com',
    storageBucket: 'cinemon-5e0e1.firebasestorage.app',
    iosBundleId: 'com.cinemon.app',
  );
}
