-- 35mm Selects, generated by tool/selects_seed.py. Do not edit by hand.
-- Needs the official account (username 35mm). Safe to re-run.
do $$ begin
  if not exists (select 1 from public.profiles where username = '35mm') then
    raise exception 'Create the official account and rename it to 35mm first.';
  end if;
end $$;

-- 1. Hong Kong, After Midnight
insert into public.lists (id, user_id, kind, title, description, visibility, is_select, select_rank, tagline, cover_style, cover_path, moods)
select '35539bd4-b6e4-56b4-baf0-5b2fdf6bd3ee', id, 'playlist', 'Hong Kong, After Midnight', 'Wong Kar-wai’s lonely hearts, John Woo’s gunfights and the cops and triads of the 2000s. Start with Chungking Express; stay for everything after.', 'public', true, 1, 'Neon, rain and heartbreak. Twelve films from the city that never sleeps.', 'film', '/8e6avmXiqurj5LHkmdHBq6rc5jm.jpg', array['late_night', 'neon']
  from public.profiles where username = '35mm'
on conflict (id) do update set title = excluded.title, description = excluded.description, is_select = true, select_rank = excluded.select_rank, tagline = excluded.tagline, cover_style = excluded.cover_style, cover_path = excluded.cover_path, moods = excluded.moods;
delete from public.list_items where list_id = '35539bd4-b6e4-56b4-baf0-5b2fdf6bd3ee';
insert into public.list_items (list_id, film_id, media_type, film_title, film_poster_path, film_backdrop_path, film_year, position) values
  ('35539bd4-b6e4-56b4-baf0-5b2fdf6bd3ee', 11104, 'movie', 'Chungking Express', '/43I9DcNoCzpyzK8JCkJYpHqHqGG.jpg', '/8e6avmXiqurj5LHkmdHBq6rc5jm.jpg', '1994', 1),
  ('35539bd4-b6e4-56b4-baf0-5b2fdf6bd3ee', 11220, 'movie', 'Fallen Angels', '/yyM9BPdwttK5LKZSLvHae7QPKo1.jpg', '/lInQVVbPjKFGX7GDcxNMXALy2Y4.jpg', '1995', 2),
  ('35539bd4-b6e4-56b4-baf0-5b2fdf6bd3ee', 843, 'movie', 'In the Mood for Love', '/8BgGbbWiLNhPtkMkN0gGTnbtvBv.jpg', '/ffQFnAUm2Uu4RU0nijpjPRf9TBT.jpg', '2000', 3),
  ('35539bd4-b6e4-56b4-baf0-5b2fdf6bd3ee', 18311, 'movie', 'Days of Being Wild', '/g0nbZt1eFlL8FqG8r524iXnpoQV.jpg', '/oBK7lTywbhvpY8AIdyS43yCVPbt.jpg', '1990', 4),
  ('35539bd4-b6e4-56b4-baf0-5b2fdf6bd3ee', 18329, 'movie', 'Happy Together', '/kO4KjUkQOfWSBw06Bdl7m6AlEP7.jpg', '/2Xkd3WeAx11cHxb4Lr3wnSNDWcd.jpg', '1997', 5),
  ('35539bd4-b6e4-56b4-baf0-5b2fdf6bd3ee', 844, 'movie', '2046', '/jIN65qw0Giplo4CshzMrxz204Wn.jpg', '/h3JAMIeywbzobkhu2rt3mQAwRR1.jpg', '2004', 6),
  ('35539bd4-b6e4-56b4-baf0-5b2fdf6bd3ee', 11471, 'movie', 'A Better Tomorrow', '/uxZIWxOm2yonHyjLARzW37aEZjF.jpg', '/mgTZFhBGOE0Qyckynhm81CQLrP2.jpg', '1986', 7),
  ('35539bd4-b6e4-56b4-baf0-5b2fdf6bd3ee', 11782, 'movie', 'Hard Boiled', '/oMqr4CGGqVlfI8DdrSelK1e9aFM.jpg', '/bL3rgYFs0NTAoLBMpCBIJ7aX6hp.jpg', '1992', 8),
  ('35539bd4-b6e4-56b4-baf0-5b2fdf6bd3ee', 10775, 'movie', 'Infernal Affairs', '/gix9thDBXfjJ8M7rYbihqbQGBcP.jpg', '/4Mm5l3TcKGynSNto0eyRJgBrkJ7.jpg', '2002', 9),
  ('35539bd4-b6e4-56b4-baf0-5b2fdf6bd3ee', 37185, 'movie', 'Comrades, Almost a Love Story', '/hjlRaJEa8zuN72LmMATQ3FcCTb0.jpg', '/zFPns25Qnt6WCM6DLQrPrNziC0e.jpg', '1996', 10),
  ('35539bd4-b6e4-56b4-baf0-5b2fdf6bd3ee', 68883, 'movie', 'Rouge', '/q2wAAeGagOmqmqEkEgveLJYBj89.jpg', '/4kpbkS9V4QJcQBnvxvRfRojdFyI.jpg', '1987', 11),
  ('35539bd4-b6e4-56b4-baf0-5b2fdf6bd3ee', 18747, 'movie', 'Election', '/js9w4pQNJq9si5AlwdvojBfC9Ml.jpg', '/uVnHskokSRJ8cRItMA0L9NQ9dXa.jpg', '2005', 12);

-- 2. The Best of British Cinema
insert into public.lists (id, user_id, kind, title, description, visibility, is_select, select_rank, tagline, cover_style, cover_path, moods)
select '6ae1013e-2d7e-5183-b4ce-2d7cf58c9c6d', id, 'playlist', 'The Best of British Cinema', 'Not a canon, a conversation. Wartime longing, post-war paranoia, kitchen-sink rage and a Glasgow flat in 1996. Watch them in order if you can.', 'public', true, 2, 'From Powell and Pressburger to Jonathan Glazer: the island’s cinema at its best.', 'film', '/rLLhOCgAjuvlKmjUqVb7P1UAbUI.jpg', array['rainy_day']
  from public.profiles where username = '35mm'
on conflict (id) do update set title = excluded.title, description = excluded.description, is_select = true, select_rank = excluded.select_rank, tagline = excluded.tagline, cover_style = excluded.cover_style, cover_path = excluded.cover_path, moods = excluded.moods;
delete from public.list_items where list_id = '6ae1013e-2d7e-5183-b4ce-2d7cf58c9c6d';
insert into public.list_items (list_id, film_id, media_type, film_title, film_poster_path, film_backdrop_path, film_year, position) values
  ('6ae1013e-2d7e-5183-b4ce-2d7cf58c9c6d', 851, 'movie', 'Brief Encounter', '/jC9EwLJcGhYMSQAHu2LxkKN5v7O.jpg', '/vKvoOlhhaZCsiGQDvaZQqyGq1oA.jpg', '1945', 1),
  ('6ae1013e-2d7e-5183-b4ce-2d7cf58c9c6d', 28162, 'movie', 'A Matter of Life and Death', '/H74LWKnhOeIFSk9gNjBcPjIov3.jpg', '/bY7DvsYsAODykqUJfkPZA3BHKOd.jpg', '1946', 2),
  ('6ae1013e-2d7e-5183-b4ce-2d7cf58c9c6d', 19542, 'movie', 'The Red Shoes', '/vPvpBWFWDvEXuQBkoYgA6A89GVp.jpg', '/Aa1jUhkenqspgGQlqbsXFax6iW.jpg', '1948', 3),
  ('6ae1013e-2d7e-5183-b4ce-2d7cf58c9c6d', 1092, 'movie', 'The Third Man', '/vqnFHTx1phgTAsLfxZoejSbMVHA.jpg', '/rLLhOCgAjuvlKmjUqVb7P1UAbUI.jpg', '1949', 4),
  ('6ae1013e-2d7e-5183-b4ce-2d7cf58c9c6d', 11898, 'movie', 'Kind Hearts and Coronets', '/eBvpyRjD3DcCsWgdV6Y9oqPS7dO.jpg', '/r7jtS16I3vgVvqapgCa7RMkZnvj.jpg', '1949', 5),
  ('6ae1013e-2d7e-5183-b4ce-2d7cf58c9c6d', 5506, 'movie', 'The Ladykillers', '/9LJ6ZV59Q92LAJAbmb7xm9dUBGU.jpg', '/bAnSOcJgNmV9aaJmFkTmkngCF3J.jpg', '1955', 6),
  ('6ae1013e-2d7e-5183-b4ce-2d7cf58c9c6d', 947, 'movie', 'Lawrence of Arabia', '/AiAm0EtDvyGqNpVoieRw4u65vD1.jpg', '/eULrEMwgXnWmzdowUfegaw2YYgD.jpg', '1962', 7),
  ('6ae1013e-2d7e-5183-b4ce-2d7cf58c9c6d', 13384, 'movie', 'Kes', '/r1FMq75irhsQBVGjXhPU4xA9SDo.jpg', '/eWvxOS5g67B1b46Cff9TlYuJleY.jpg', '1970', 8),
  ('6ae1013e-2d7e-5183-b4ce-2d7cf58c9c6d', 931, 'movie', 'Don''t Look Now', '/ivWsU3QtcstImCTOjItsH0SAbNn.jpg', '/8qi3gplNf48uLZnne09iiL4OvFG.jpg', '1973', 9),
  ('6ae1013e-2d7e-5183-b4ce-2d7cf58c9c6d', 14807, 'movie', 'The Long Good Friday', '/pXS667me5Jfoj1b0xuxgjEMKunF.jpg', '/vXjf4iCdZB1OvNQuJZyKeSkVWlH.jpg', '1980', 10),
  ('6ae1013e-2d7e-5183-b4ce-2d7cf58c9c6d', 13446, 'movie', 'Withnail & I', '/i18cIp8A10A2JgByrfA9oIC9299.jpg', '/bOgKCymrdPHPHozhRBNr9XhVD87.jpg', '1987', 11),
  ('6ae1013e-2d7e-5183-b4ce-2d7cf58c9c6d', 11159, 'movie', 'Secrets & Lies', '/zQBuRQ3hrLhkEsXcxteUxuxLrvs.jpg', '/oLh3r9BhrymkMjKtI2geTGkKMif.jpg', '1996', 12),
  ('6ae1013e-2d7e-5183-b4ce-2d7cf58c9c6d', 627, 'movie', 'Trainspotting', '/1jUC02qsqS2NxBMFarbIhcQtazV.jpg', '/dkfBKDUIWP1peEszdqK10MkMZCP.jpg', '1996', 13),
  ('6ae1013e-2d7e-5183-b4ce-2d7cf58c9c6d', 11826, 'movie', 'Sexy Beast', '/xTfCZTzhgHNAR1pf5D49WH4buI5.jpg', '/yYUGy4MDM6jbJoamlfo3HT6Guhy.jpg', '2001', 14),
  ('6ae1013e-2d7e-5183-b4ce-2d7cf58c9c6d', 97370, 'movie', 'Under the Skin', '/55wmcXJIDYITr7JDijJTdvwSaAv.jpg', '/eS5OdKN3kRZXQbWRSSCJ4Gh0z26.jpg', '2014', 15);

-- 3. Old Bollywood
insert into public.lists (id, user_id, kind, title, description, visibility, is_select, select_rank, tagline, cover_style, cover_path, moods)
select 'e9d4a625-2b7b-59de-bdce-323bbc8a707b', id, 'playlist', 'Old Bollywood', 'Raj Kapoor’s tramps, Guru Dutt’s poets, Madhubala’s Anarkali and the angry young man. The golden age, in fourteen films.', 'public', true, 3, 'Songs, stars and heartbreak, 1951–1975.', 'film', '/mUAvhPWY4r7O32txXa7VvzKMrhJ.jpg', array['heartbreaking', 'epic']
  from public.profiles where username = '35mm'
on conflict (id) do update set title = excluded.title, description = excluded.description, is_select = true, select_rank = excluded.select_rank, tagline = excluded.tagline, cover_style = excluded.cover_style, cover_path = excluded.cover_path, moods = excluded.moods;
delete from public.list_items where list_id = 'e9d4a625-2b7b-59de-bdce-323bbc8a707b';
insert into public.list_items (list_id, film_id, media_type, film_title, film_poster_path, film_backdrop_path, film_year, position) values
  ('e9d4a625-2b7b-59de-bdce-323bbc8a707b', 39039, 'movie', 'Awaara', '/njaaQO1JZRtypogw5IPLtTlOSLI.jpg', '/2MWe3NWuwF91Aidc5gm5vNKeteS.jpg', '1951', 1),
  ('e9d4a625-2b7b-59de-bdce-323bbc8a707b', 48929, 'movie', 'Shree 420', '/nKqpOzyDhZvpGUDkUK8aY4treLg.jpg', '/totcmnBIkwJHqutFu26N8JO5jDU.jpg', '1955', 2),
  ('e9d4a625-2b7b-59de-bdce-323bbc8a707b', 41053, 'movie', 'Pyaasa', '/lQu1gBTKIF4BGC0f3GZPEbQYzWq.jpg', '/hvtRa9AZ2mKnR32fRow356vsdSf.jpg', '1957', 3),
  ('e9d4a625-2b7b-59de-bdce-323bbc8a707b', 917, 'movie', 'Mother India', '/AlfM9yLcK1rhv73iNbDiOU9vnnu.jpg', '/bkzPygcInZMOKpnNhSHlbqVNinJ.jpg', '1957', 4),
  ('e9d4a625-2b7b-59de-bdce-323bbc8a707b', 168069, 'movie', 'Madhumati', '/vrrQ69whukrcuuFi7Oo7PjBaJ2K.jpg', '/6YKiSNSxatKGm1f4PhlimDOqKz1.jpg', '1958', 5),
  ('e9d4a625-2b7b-59de-bdce-323bbc8a707b', 53767, 'movie', 'Kaagaz Ke Phool', '/aBdEEAKEuzcvk8IKsHfbz3KSitZ.jpg', '/jKmX5N1jr36MCYbW9XOi93xymGM.jpg', '1959', 6),
  ('e9d4a625-2b7b-59de-bdce-323bbc8a707b', 44519, 'movie', 'Mughal-e-Azam', '/lKfNZUh9CRp1EHjxgNGtrbvm55.jpg', '/1U4V92gwVDnVjWJn6eMciOffClN.jpg', '1960', 7),
  ('e9d4a625-2b7b-59de-bdce-323bbc8a707b', 80484, 'movie', 'Guide', '/a31qY8UA4hsJdwFrollZ1iRzukC.jpg', '/9hXAAN4xUdXlr0gPwAtKztnEUDt.jpg', '1965', 8),
  ('e9d4a625-2b7b-59de-bdce-323bbc8a707b', 108286, 'movie', 'Teesri Manzil', '/nibr8V7SWtBUJASFlRJmCE6BbLY.jpg', '/xT58IXwDTRVbrSgfmUmQ8MClR9Q.jpg', '1966', 9),
  ('e9d4a625-2b7b-59de-bdce-323bbc8a707b', 96732, 'movie', 'Aradhana', '/wpAYC3kWt9VpDDY2a3jWt4sF3wc.jpg', '/7CTx02MMqqcOBFsSCWM3HSbI20X.jpg', '1969', 10),
  ('e9d4a625-2b7b-59de-bdce-323bbc8a707b', 26237, 'movie', 'Anand', '/vgrege8e0yk3SSdHzHfMTvk2ffc.jpg', '/uZEN5R7s3IvZlt29uTEhpnOAyZd.jpg', '1971', 11),
  ('e9d4a625-2b7b-59de-bdce-323bbc8a707b', 54966, 'movie', 'Pakeezah', '/dVm7WcvVfeQzi8M7NZXcdtbF6jz.jpg', '/saEcTHiuQgQefEMKZpWUHTH53ik.jpg', '1972', 12),
  ('e9d4a625-2b7b-59de-bdce-323bbc8a707b', 22460, 'movie', 'Deewaar', '/pwzfljCp52jieXTBE0lynz7bu2g.jpg', '/lx94BR9gILXSGptjaUSUPveBjJu.jpg', '1975', 13),
  ('e9d4a625-2b7b-59de-bdce-323bbc8a707b', 12259, 'movie', 'Sholay', '/ya9bwgqA4eNl5bQ9QqS0jcmRoBS.jpg', '/mUAvhPWY4r7O32txXa7VvzKMrhJ.jpg', '1975', 14);

-- 4. Slow-Burn Thrillers
insert into public.lists (id, user_id, kind, title, description, visibility, is_select, select_rank, tagline, cover_style, cover_path, moods)
select '6b304481-48e3-58aa-93c6-06ea32e2a868', id, 'playlist', 'Slow-Burn Thrillers', 'Films that take their time and then take the floor out from under you. Best watched late, with your phone in another room.', 'public', true, 4, 'Patience, rewarded.', 'film', '/3zCPI4JFc54xvLaJ71oI2KoP3az.jpg', array['slow_burn', 'unsettling']
  from public.profiles where username = '35mm'
on conflict (id) do update set title = excluded.title, description = excluded.description, is_select = true, select_rank = excluded.select_rank, tagline = excluded.tagline, cover_style = excluded.cover_style, cover_path = excluded.cover_path, moods = excluded.moods;
delete from public.list_items where list_id = '6b304481-48e3-58aa-93c6-06ea32e2a868';
insert into public.list_items (list_id, film_id, media_type, film_title, film_poster_path, film_backdrop_path, film_year, position) values
  ('6b304481-48e3-58aa-93c6-06ea32e2a868', 592, 'movie', 'The Conversation', '/dHqVBwcv1SGymOpUueRoKzcmdes.jpg', '/s7yfiwIshKQIT6M8ZcTnFKXHs8B.jpg', '1974', 1),
  ('6b304481-48e3-58aa-93c6-06ea32e2a868', 11644, 'movie', 'Blow Out', '/uFzMscVLDrTaYd6KXOXlr6dly7w.jpg', '/nk87CtgZ7wd86W37oJHGYAJbmLz.jpg', '1981', 2),
  ('6b304481-48e3-58aa-93c6-06ea32e2a868', 8740, 'movie', 'The Vanishing', '/eE5bbuRJluooG2MjEAsLEYyuJoa.jpg', '/gcXbxHjkUwLV4HrE2oJcbP7UGTA.jpg', '1988', 3),
  ('6b304481-48e3-58aa-93c6-06ea32e2a868', 36095, 'movie', 'Cure', '/xNVJr9q6AtSbjosS6Ed9YirOkSo.jpg', '/xxIRKSd9LmHojUD5grvMuGypwVC.jpg', '1997', 4),
  ('6b304481-48e3-58aa-93c6-06ea32e2a868', 11423, 'movie', 'Memories of Murder', '/jcgUjx1QcupGzjntTVlnQ15lHqy.jpg', '/6Kn6qW3an3DkPl3MahWemTzrjCt.jpg', '2003', 5),
  ('6b304481-48e3-58aa-93c6-06ea32e2a868', 445, 'movie', 'Caché', '/vTzjRi0Uhy0tt3Rjw8SARZZJHlX.jpg', '/mOYIUiSdoLWynoZIGDZSAAUZ3ss.jpg', '2005', 6),
  ('6b304481-48e3-58aa-93c6-06ea32e2a868', 1949, 'movie', 'Zodiac', '/6YmeO4pB7XTh8P8F960O1uA14JO.jpg', '/3zCPI4JFc54xvLaJ71oI2KoP3az.jpg', '2007', 7),
  ('6b304481-48e3-58aa-93c6-06ea32e2a868', 49517, 'movie', 'Tinker Tailor Soldier Spy', '/e0dZ7TapGY9HtJ9xk1TUHPEOccl.jpg', '/6ZwscHN0bSIueTVTo6mlTGUUP90.jpg', '2011', 8),
  ('6b304481-48e3-58aa-93c6-06ea32e2a868', 146233, 'movie', 'Prisoners', '/uhviyknTT5cEQXbn6vWIqfM4vGm.jpg', '/3RFmTz5h2UuFWEV4oH00XICBR9y.jpg', '2013', 9),
  ('6b304481-48e3-58aa-93c6-06ea32e2a868', 181886, 'movie', 'Enemy', '/vf40tyDRKZsBmaLsYeopzfFLzLx.jpg', '/deYWtXTc56YdXyIuuMuA8dvBY16.jpg', '2014', 10),
  ('6b304481-48e3-58aa-93c6-06ea32e2a868', 491584, 'movie', 'Burning', '/kXiF80o74fE9gf3Utf9moAI7ar0.jpg', '/qQEt2FqF8McryFBNX30dyDJKiEK.jpg', '2018', 11);

-- 5. The Canon, Briefly
insert into public.lists (id, user_id, kind, title, description, visibility, is_select, select_rank, tagline, cover_style, cover_path, moods)
select '4f79ff75-f7be-5e8b-95b2-56ede55e06a5', id, 'playlist', 'The Canon, Briefly', 'If you have never watched an old film on purpose, start here. Each one is here because it is still thrilling, not because it is homework.', 'public', true, 5, 'Twelve films critics keep coming back to. A place to start, not an exam.', 'film', '/w5IDXtifKntw0ajv2co7jFlTQDM.jpg', array['epic']
  from public.profiles where username = '35mm'
on conflict (id) do update set title = excluded.title, description = excluded.description, is_select = true, select_rank = excluded.select_rank, tagline = excluded.tagline, cover_style = excluded.cover_style, cover_path = excluded.cover_path, moods = excluded.moods;
delete from public.list_items where list_id = '4f79ff75-f7be-5e8b-95b2-56ede55e06a5';
insert into public.list_items (list_id, film_id, media_type, film_title, film_poster_path, film_backdrop_path, film_year, position) values
  ('4f79ff75-f7be-5e8b-95b2-56ede55e06a5', 5156, 'movie', 'Bicycle Thieves', '/iPdVqIpmR3bRvOQJPrn4pr2KR3q.jpg', '/nd6ItWuWGmTKhHXuxVC8kp86CmQ.jpg', '1948', 1),
  ('4f79ff75-f7be-5e8b-95b2-56ede55e06a5', 18148, 'movie', 'Tokyo Story', '/g2YbTYKpY7N2yDSk7BfXZ18I5QV.jpg', '/jLq0ol1f0ZKXni9R9GsPBcyPrNN.jpg', '1953', 2),
  ('4f79ff75-f7be-5e8b-95b2-56ede55e06a5', 346, 'movie', 'Seven Samurai', '/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg', '/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg', '1954', 3),
  ('4f79ff75-f7be-5e8b-95b2-56ede55e06a5', 426, 'movie', 'Vertigo', '/15uOEfqBNTVtDUT7hGBVCka0rZz.jpg', '/rtVwkTqllcmyY4TVOycgVBHppWf.jpg', '1958', 4),
  ('4f79ff75-f7be-5e8b-95b2-56ede55e06a5', 15, 'movie', 'Citizen Kane', '/sav0jxhqiH0bPr2vZFU0Kjt2nZL.jpg', '/ruF3Lmd4A8MHbnEBE6lxPMbsHGL.jpg', '1941', 5),
  ('4f79ff75-f7be-5e8b-95b2-56ede55e06a5', 872, 'movie', 'Singin'' in the Rain', '/671EPwBsHGHBk0cdOeZqmOK0XB3.jpg', '/6qOyw4yfzbzTp5YsCX26C28Do0S.jpg', '1952', 6),
  ('4f79ff75-f7be-5e8b-95b2-56ede55e06a5', 422, 'movie', '8½', '/23VIf7zNxAgaXwIlvzd3IvOd9sY.jpg', '/y2FNZLHynsevBnVTocGW6c3pQpr.jpg', '1963', 7),
  ('4f79ff75-f7be-5e8b-95b2-56ede55e06a5', 797, 'movie', 'Persona', '/cl0HEZT8UfzLqaMrYTvGNHOfPYj.jpg', '/amr72SENYz7AM4Hq5WBXxFBJEY6.jpg', '1966', 8),
  ('4f79ff75-f7be-5e8b-95b2-56ede55e06a5', 62, 'movie', '2001: A Space Odyssey', '/ve72VxNqjGM69Uky4WTo2bK6rfq.jpg', '/w5IDXtifKntw0ajv2co7jFlTQDM.jpg', '1968', 9),
  ('4f79ff75-f7be-5e8b-95b2-56ede55e06a5', 238, 'movie', 'The Godfather', '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg', '1972', 10),
  ('4f79ff75-f7be-5e8b-95b2-56ede55e06a5', 1018, 'movie', 'Mulholland Drive', '/x7A59t6ySylr1L7aubOQEA480vM.jpg', '/g9ClaS5EqU0Hk8WIbMNhld0Bk6f.jpg', '2001', 11),
  ('4f79ff75-f7be-5e8b-95b2-56ede55e06a5', 843, 'movie', 'In the Mood for Love', '/8BgGbbWiLNhPtkMkN0gGTnbtvBv.jpg', '/ffQFnAUm2Uu4RU0nijpjPRf9TBT.jpg', '2000', 12);

-- 6. Tokyo, Quietly
insert into public.lists (id, user_id, kind, title, description, visibility, is_select, select_rank, tagline, cover_style, cover_path, moods)
select '3a51bdcf-f1a9-5f10-a97b-8db0bdefc0f8', id, 'playlist', 'Tokyo, Quietly', 'Ozu’s families, Kore-eda’s found ones, and a toilet cleaner who loves trees. Japanese films for when you want to feel everything, slowly.', 'public', true, 6, 'Small rooms, long takes, whole lives.', 'film', '/hjWxngV6tidwDkfJDEgMjHD2KEz.jpg', array['tender']
  from public.profiles where username = '35mm'
on conflict (id) do update set title = excluded.title, description = excluded.description, is_select = true, select_rank = excluded.select_rank, tagline = excluded.tagline, cover_style = excluded.cover_style, cover_path = excluded.cover_path, moods = excluded.moods;
delete from public.list_items where list_id = '3a51bdcf-f1a9-5f10-a97b-8db0bdefc0f8';
insert into public.list_items (list_id, film_id, media_type, film_title, film_poster_path, film_backdrop_path, film_year, position) values
  ('3a51bdcf-f1a9-5f10-a97b-8db0bdefc0f8', 20530, 'movie', 'Late Spring', '/iNtRSY2AGjW1VDXDR79bKsNUdus.jpg', '/sKEncrsqPxibvlWbsXYsPhXGBjw.jpg', '1949', 1),
  ('3a51bdcf-f1a9-5f10-a97b-8db0bdefc0f8', 18148, 'movie', 'Tokyo Story', '/g2YbTYKpY7N2yDSk7BfXZ18I5QV.jpg', '/jLq0ol1f0ZKXni9R9GsPBcyPrNN.jpg', '1953', 2),
  ('3a51bdcf-f1a9-5f10-a97b-8db0bdefc0f8', 3782, 'movie', 'Ikiru', '/dgNTS4EQDDVfkzJI5msKuHu2Ei3.jpg', '/pQ06lTkmJd1mbotdl847HoV2iaA.jpg', '1952', 3),
  ('3a51bdcf-f1a9-5f10-a97b-8db0bdefc0f8', 46918, 'movie', 'Floating Weeds', '/nLepKtb48XSnPQNsuS4svbtNBY7.jpg', '/o7l1P351p4gh9dTlcQy1xB8NL8H.jpg', '1959', 4),
  ('3a51bdcf-f1a9-5f10-a97b-8db0bdefc0f8', 11830, 'movie', 'Tampopo', '/ArYdSuX3zY9fMsE4LqmBl7xJq5R.jpg', '/oq8HM9TOSbH54Xy0OBJGzYrtUC7.jpg', '1985', 5),
  ('3a51bdcf-f1a9-5f10-a97b-8db0bdefc0f8', 18872, 'movie', 'Maborosi', '/ri9sequtTo9K8I6AQoRbbBzU8F2.jpg', '/bk8RQN88Hh5jusTKydxCJfDlDNg.jpg', '1995', 6),
  ('3a51bdcf-f1a9-5f10-a97b-8db0bdefc0f8', 17962, 'movie', 'After Life', '/bs2M1hqAQl5LeAOPPRV4drwouZS.jpg', '/pXOsdvH4xuprxGmZMiCJsRAowi7.jpg', '1999', 7),
  ('3a51bdcf-f1a9-5f10-a97b-8db0bdefc0f8', 25050, 'movie', 'Still Walking', '/FWJbhAPdwiwKhUaAyz841jpYa1.jpg', '/lvSB0bnLzuxwrfTlI2l13gctWRn.jpg', '2008', 8),
  ('3a51bdcf-f1a9-5f10-a97b-8db0bdefc0f8', 505192, 'movie', 'Shoplifters', '/4nfRUOv3LX5zLn98WS1WqVBk9E9.jpg', '/dVRkhmtDn3EiyhX6c9SfL7klCoU.jpg', '2018', 9),
  ('3a51bdcf-f1a9-5f10-a97b-8db0bdefc0f8', 758866, 'movie', 'Drive My Car', '/znXps7wPyYq8UDCfeyO2vfEIeRS.jpg', '/r6aqhlmJmu8Dv5E7QYEruaEXKYm.jpg', '2021', 10),
  ('3a51bdcf-f1a9-5f10-a97b-8db0bdefc0f8', 976893, 'movie', 'Perfect Days', '/tvUHVSTJV9ITON3oyHaWp7oaAc8.jpg', '/hjWxngV6tidwDkfJDEgMjHD2KEz.jpg', '2023', 11);
